Lint flow.js
kupibilet-frontend/eslint-config-kupibilet pull request #41
Opened 2019-02-26 14:05 UTC by loonywizard

Поняли что у нас не линтятся описания типов flow, экспериментируем с конфигом, чтобы был нормальные кодстаел

2019-02-26 15:15 UTC, nezed requested changes

2019-02-26 15:15 UTC, nezed commented on .eslintrc.js
> +    'plugin:flowtype/recommended',
Смотри как славненько

https://github.com/kupibilet-frontend/eslint-config-kupibilet/blob/master/rules/async-await-promises.yml#L1-L2

2019-02-26 15:27 UTC, loonywizard commented on .eslintrc.js
> +    'plugin:flowtype/recommended',
я вот так пробовал и ничего не линтилось, если добавить `/recommended` то валится с ошибкой

```
plugins:
  - flowtype
```

2019-02-26 15:38 UTC, nezed commented on .eslintrc.js
> +    'plugin:flowtype/recommended',
extends и plugins — очень разные вещи

В терминах костыля этого пакета должно звучать так:
```
extends:
    - plugin:flowtype/recommended

2019-03-12 09:19 UTC, nezed commented
Этот PR вносит новые ошибки - ломающее обратную совместимость.
Варианта тут два:

1. Переделать все правила на ворнинги и добавить TODO (и это будет правильно)
1. Смёржим это в новую мажёрную версию и будем болезненно на неё обновляться (надеюсь ты помнишь, у нас есть проекты которые полноценно линтят код)

2019-03-27 15:10 UTC, nezed commented on tests/flow-linting.js
> +  age: 20,
Увековечил себя молодым)

2019-03-27 15:11 UTC, nezed approved these changes

2019-03-27 15:11 UTC, merged